version: '3'
services:
  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-fronting
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  server1:
    build:
      context: .
      dockerfile: Dockerfile-grpc-server
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
          aliases:
            - service1
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"

  server2:
    build:
      context: .
      dockerfile: Dockerfile-grpc-server
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
          aliases:
            - service2
    environment:
      - SERVICE_NAME=2
    expose:
      - "80"
networks:
  envoymesh: {}