version: '3'
services:
  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-fronting
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
      - ./private.pem:/certs/test.key
      - ./public.pem:/certs/test.crt
    networks:
      - envoymesh
    expose:
      - "443"
      - "8001"
    ports:
      - "443:443"
      - "8001:8001"

  server1:
    build:
      context: .
      dockerfile: Dockerfile-grpc-server
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
          aliases:
            - service1
    environment:
      - SERVICE_NAME=1
      - PORT=80
    expose:
      - "80"
    ports:
      - "3002:80"

  server2:
    build:
      context: .
      dockerfile: Dockerfile-grpc-server
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
          aliases:
            - service2
    environment:
      - SERVICE_NAME=2
      - PORT=80
    expose:
      - "80"
    ports:
      - "3003:80"
networks:
  envoymesh: {}
